language : php

php :
  - '7.0'

env :
  global : 
    - 'FTP_USER=labsroom'
    - 'FTP_PASS=bismilah'
    
script:
  - "curl -u $FTP_USER:$FTP_PASS ftp://file.000webhost.com -Q 'mkd public_html/'"
  - "curl -T coba.php $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html'"